export const DEFAULT_UI_LOCALE = "en";

const UI_COPY = {
  en: {
    brandTitle: "OpenVibeCoding",
    brandSubtitle: "plan / delegate / track / resume / prove",
    dashboard: {
      homePhase2: {
        heroTitle: "The open command tower for AI engineering",
        heroSubtitle:
          "Stop babysitting AI coding work. AI coding does not lack models. It lacks a command tower. OpenVibeCoding gives teams one governed operator path to plan, delegate, track, resume, and prove long-running engineering work across Codex and Claude Code.",
        startFirstTaskLabel: "Start first task",
        startNewTaskLabel: "Start new task",
        viewLatestRunsLabel: "View latest runs",
        investigateHighRiskFailuresLabel: "Investigate high-risk failures",
        handleLatestFailureLabel: "Handle latest failure",
        productSpineTitle: "One open command tower, five moves",
        productSpineDescription:
          "Start from the live command deck, not the adoption catalog. The loop stays simple: plan, delegate, track, resume, and prove through Command Tower, Workflow Cases, and Proof & Replay.",
        productSpineCards: [
          {
            href: "/command-tower",
            title: "Command Tower",
            desc: "Watch governed AI agents and MCP-driven work move through one operator surface.",
          },
          {
            href: "/workflows",
            title: "Workflow Cases",
            desc: "Track the case record that ties request, queue, verdict, proof, and linked runs together.",
          },
          {
            href: "/runs",
            title: "Proof & Replay",
            desc: "Inspect evidence bundles, compare reruns, and replay failures before you trust the result.",
          },
        ],
        publicTemplatesTitle: "One proven workflow, two showcase expansions",
        publicTemplatesDescription:
          "Start with `news_digest` first. It is the official public baseline. `topic_brief` and `page_brief` stay useful, but they are still showcase paths until they earn their own healthy proof bundles.",
        publicTemplatesActionLabel: "Open proof pack",
        publicTemplatesActionHref: "/use-cases/",
        publicTemplateCards: [
          {
            href: "/pm?template=news_digest",
            badge: "Release-proven first run",
            title: "news_digest",
            desc: "Generate a news summary around one topic from public sources while keeping the evidence auditable.",
            bestFor: "Use when you want the fastest proof-oriented public path.",
            example: "Seattle tech and AI + 3 source domains + 24h",
            proof: "Proof state: official public baseline",
            fields: ["topic", "sources[]", "time_range", "max_results"],
          },
          {
            href: "/pm?template=topic_brief",
            badge: "Public showcase",
            title: "topic_brief",
            desc: "Open a bounded topic brief as a read-only workflow case with search-backed proof.",
            bestFor: "Use when you want a narrow brief around one topic and a recent time window.",
            example: "Seattle tech and AI + 7d + 5 results",
            proof: "Proof state: public, but not yet release-proven",
            fields: ["topic", "time_range", "max_results"],
          },
          {
            href: "/pm?template=page_brief",
            badge: "Public showcase",
            title: "page_brief",
            desc: "Capture one URL as a read-only workflow case with browser-backed evidence.",
            bestFor: "Use when one page matters more than a whole search topic.",
            example: "https://example.com + focused summary request",
            proof: "Proof state: browser-backed showcase path",
            fields: ["url", "focus"],
          },
        ],
        publicAdvantagesTitle: "Three engineering layers behind the command tower",
        publicAdvantagesDescription:
          "Prompt 5 keeps the public story anchored on proof, replay, read-only MCP access, and explainable operator review instead of generic AI claims.",
        publicAdvantageCards: [
          {
            href: "/runs",
            title: "Prompt Engineering",
            desc: "Every first-run case still lands on evidence, compare, and replay before you trust the output.",
          },
          {
            href: "/runs",
            title: "Context Engineering",
            desc: "Run Detail and Run Compare now explain what changed, why it matters, and the next operator step.",
          },
          {
            href: "/workflows",
            title: "Harness Engineering",
            desc: "Workflow Cases are now moving toward reusable assets instead of staying trapped as one-off detail pages.",
          },
        ],
        ecosystemTitle: "Works with today's coding-agent ecosystem",
        ecosystemDescription:
          "Keep the front door anchored on Codex, Claude Code, and read-only MCP. Mention OpenHands and comparison-only tools in the ecosystem layer, not in the hero.",
        ecosystemAction: "Open ecosystem map",
        ecosystemActionHref: "/ecosystem/",
        ecosystemCards: [
          {
            badge: "Primary workflow binding",
            title: "Codex workflows",
            desc: "Use OpenVibeCoding when Codex-driven work needs one command tower, one case record, and one replayable proof path.",
            href: "/command-tower",
            prefetch: true,
          },
          {
            badge: "Primary workflow binding",
            title: "Claude Code workflows",
            desc: "The same operator surface works for Claude Code-style coding loops that need governed visibility, approvals, and evidence before promotion.",
            href: "/command-tower",
            prefetch: true,
          },
          {
            badge: "Protocol surface",
            title: "Read-only MCP",
            desc: "MCP is a real protocol surface here, but the current boundary is read-only. External tools can inspect truth without mutating it.",
            href: "/runs",
            prefetch: true,
          },
          {
            badge: "Adjacent ecosystem",
            title: "OpenHands and comparison layer",
            desc: "OpenHands belongs in the broader ecosystem layer, while OpenCode stays comparison-only and OpenClaw stays out of the main front door.",
            href: "/ecosystem/",
          },
        ],
        integrationTitle: "Choose the right adoption path",
        integrationDescription:
          "Use the compatibility matrix as the main router, keep the proof-first guide as the fastest way to believe the product story, then open protocol, playbooks, packages, or AI surfaces only after the real job is clear.",
        proofFirstActionLabel: "See first proven workflow",
        proofFirstActionHref: "/use-cases/",
        integrationCards: [
          {
            badge: "Decision layer",
            title: "Compatibility matrix",
            desc: "Use one routing page to compare Codex, Claude Code, OpenClaw, read-only MCP, skills, and builder entrypoints before you choose a deeper path.",
            href: "/compatibility/",
          },
          {
            badge: "Truthful adoption map",
            title: "Integration guide",
            desc: "Use the integration guide when you need the deeper truthful answer for Codex, Claude Code, and OpenClaw positioning.",
            href: "/integrations/",
          },
          {
            badge: "Repo-owned playbooks",
            title: "Skills quickstart",
            desc: "Use the skills guide when your team needs repeatable playbooks instead of guessing from the `.agents/skills/` tree.",
            href: "/skills/",
          },
        ],
        aiSurfacesTitle: "AI surfaces in the real workflow",
        aiSurfacesDescription:
          "AI in OpenVibeCoding is not a floating chat box. It already shows up as a pre-run advisor, a workflow-level explainer, and a run/compare operator brief.",
        aiSurfacesActionLabel: "Open AI + MCP + API surfaces",
        aiSurfacesActionHref: "/ai-surfaces/",
        aiSurfaceCards: [
          {
            badge: "Pre-run advisory",
            title: "Flight Plan copilot",
            desc: "PM intake can preview one bounded pre-run brief before execution starts, so approval and evidence expectations are visible early.",
            href: "/pm",
            prefetch: true,
          },
          {
            badge: "Workflow-level AI",
            title: "Workflow copilot",
            desc: "Workflow Cases already expose a workflow-scoped brief that explains queue posture, latest run context, and next operator action.",
            href: "/workflows",
            prefetch: true,
          },
          {
            badge: "Run-time AI",
            title: "Run and compare operator brief",
            desc: "Run Detail and compare surfaces can already explain deltas, proof, incident context, and the next action without pretending to execute recovery.",
            href: "/runs",
            prefetch: true,
          },
        ],
        builderTitle: "Builder entrypoints",
        builderDescription:
          "This is not a full SDK platform, but the builder entrypoints now include the read-only MCP quickstart, the API and contract quickstart, and the package-level client/shared surfaces.",
        builderQuickstartCtaLabel: "Open builder quickstart",
        builderQuickstartCtaHref: "/builders/",
        builderCards: [
          {
            badge: "Protocol quickstart",
            title: "Read-only MCP quickstart",
            desc: "Start here when you want the smallest truthful map for Codex and Claude Code workflow inspection before you read package internals.",
            href: "/mcp/",
          },
          {
            badge: "API quickstart",
            title: "API and contract quickstart",
            desc: "Start here when you want OpenAPI, contract-facing types, and the thin client entrypoint before you pick a package surface.",
            href: "/api/",
          },
          {
            badge: "Thin client surface",
            title: "@cortexpilot/frontend-api-client",
            desc: "Use the dashboard, desktop, and web client entry points when you want runs, Workflow Cases, approvals, and Command Tower reads from one import boundary.",
            href: "https://github.com/xiaojiou176-open/OpenVibeCoding/blob/main/packages/frontend-api-client/README.md",
          },
          {
            badge: "Contract-facing",
            title: "@cortexpilot/frontend-api-contract",
            desc: "Use the contract package README first when you want the human guide to the generated API boundary before opening raw type files.",
            href: "https://github.com/xiaojiou176-open/OpenVibeCoding/blob/main/packages/frontend-api-contract/docs/README.md",
          },
          {
            badge: "Presentation substrate",
            title: "@cortexpilot/frontend-shared",
            desc: "Use the shared brand copy, locale helpers, status presentation, and frontend-only types instead of rebuilding those surfaces per app.",
            href: "https://github.com/xiaojiou176-open/OpenVibeCoding/blob/main/packages/frontend-shared/README.md",
          },
        ],
        liveCaseGalleryTitle: "Live Workflow Case gallery",
        liveCaseGalleryDescription:
          "Use real Workflow Cases as lightweight showcase assets. This baseline links to live case detail and share-ready recap instead of inventing demo-only gallery data.",
        liveCaseGalleryActionLabel: "Open Workflow Cases",
        liveCaseGalleryActionHref: "/workflows",
        firstTaskGuideTitle: "First-task guide (expandable)",
        firstTaskGuideDescription:
          "Start with the request, watch Command Tower, confirm the Workflow Case, then inspect Proof & Replay. It stays collapsed by default to keep the first screen quiet.",
        firstTaskGuideSummary: "Show the four-step first-task flow",
        firstTaskGuideSteps: [
          {
            href: "/pm",
            prefetch: true,
            step: "Step 1",
            title: "Describe the request (goal + acceptance)",
            desc: "State the goal and acceptance target in one sentence, then let the system open the session.",
          },
          {
            href: "/command-tower",
            prefetch: false,
            step: "Step 2",
            title: "Watch live progress (confirm it is moving)",
            desc: "Open Command Tower and confirm the run is advancing instead of getting stuck.",
          },
          {
            href: "/workflows",
            prefetch: true,
            step: "Step 3",
            title: "Confirm the Workflow Case",
            desc: "Open Workflow Cases to confirm the durable case record, queue posture, and linked runs.",
          },
          {
            href: "/runs",
            prefetch: true,
            step: "Step 4",
            title: "Inspect Proof & Replay",
            desc: "Open the run ledger to inspect status, evidence, compare state, and replay state.",
          },
        ],
        optionalApprovalStep: {
          href: "/god-mode",
          prefetch: true,
          step: "Optional",
          title: "Approval checkpoint (only when review is required)",
          desc: "Use Quick approval to confirm the blocked step and complete the final release.",
        },
      },
      skipToMainContent: "Skip to dashboard content",
      navigationAriaLabel: "Dashboard navigation",
      topbarTitle: "AI engineering command tower",
      platformStatusAriaLabel: "Platform status overview",
      lowFrequencyToolsLabel: "Low-frequency tools",
      localeToggleAriaLabel: "Switch to Chinese",
      localeToggleButtonLabel: "中文",
      badges: {
        governanceView: "Governance view",
        liveVerificationRequired: "Live verification required",
        pageLevelStatus: "Page-level status",
      },
      approval: {
        pageTitle: "Manual approvals",
        pageSubtitle: "Review every HUMAN_APPROVAL_REQUIRED item in one place before resuming execution.",
        panelTitle: "God Mode",
        panelIntro: "God Mode separates pending approvals, read-only role gaps, and queue load failures. A quiet queue is not proof that approvals are globally unnecessary.",
        roleConfigurationAriaLabel: "Approval role configuration",
        operatorRoleLabel: "Operator role",
        operatorRoleUnconfigured: "Not configured",
        refreshPending: "Refresh pending approvals",
        refreshingPending: "Refreshing...",
        lastSuccessfulRefreshPrefix: "Last successful refresh:",
        actionsDisabledTitle: "Approval actions are read-only right now.",
        queueLoadingBadge: "Refreshing",
        queueLoadFailedBadge: "Load failed",
        queueIdleBadge: "No pending items",
        queuePendingBadge: (count) => `${count} pending approvals`,
        pendingTruthUnavailable: (error) => `Pending approval truth is unavailable: ${error}`,
        recoveryTip: "Recovery tip: confirm the login state and approval role before retrying.",
        lastAttemptPrefix: "Last attempt:",
        retryFetch: "Retry fetch",
        retryingFetch: "Retrying...",
        inspectConnection: "Open PM session to inspect connection",
        verifyAuthState: "Open Command Tower to verify auth state",
        loadingPending: "Loading pending approvals...",
        pendingQueueAriaLabel: "Pending approvals queue",
        reasonLabel: "Reason",
        requiredActionLabel: "Required action",
        resumeAtLabel: "Resume at",
        continueButton: "I am done, continue",
        continuingButton: "Approving...",
        manualHint: "When the event stream shows HUMAN_APPROVAL_REQUIRED, paste the run_id and approve it. The action will be written to the event log.",
        runIdLabel: "Run ID",
        runIdPlaceholder: "Paste run_id...",
        approveButton: "Approve",
        approvingButton: "Approving...",
        confirmTitle: "Confirm approval",
        confirmDescription: (runId) => `Approve ${runId} to continue execution? This action writes to the event log and cannot be undone.`,
        cancel: "Cancel",
        confirmApproval: "Confirm approval",
        statusRefreshingQueue: "Refreshing pending approvals queue...",
        statusRetryingQueue: "Retrying pending approvals queue...",
        statusQueueRefreshed: (count) => `Pending approvals queue refreshed. ${count} item(s).`,
        statusRefreshFailed: (message, authError) => authError
            ? `Pending approvals queue refresh failed: ${message}. Confirm permissions or sign in again before retrying.`
            : "Pending approvals queue refresh failed. Resolve the error and retry.",
        statusRetryFailed: (message, authError) => authError
            ? `Retry failed: ${message}. Confirm permissions or sign in again before retrying.`
            : `Retry failed: ${message}.`,
        statusEnterRunId: "Enter run_id before approving.",
        statusSubmittingApproval: "Submitting approval...",
        statusApproved: "Approved.",
        statusFailed: (message) => `Failed: ${message}`,
      },
      sectionPrimary: "Core loop",
      sectionAdvanced: "Command deck",
      labels: {
        overview: "Overview",
        pmIntake: "PM intake",
        commandTower: "Command Tower",
        runs: "Proof & Replay",
        quickApproval: "Quick approval",
        search: "Search",
        agents: "Role desk",
        workflowCases: "Workflow Cases",
        events: "Events",
        reviews: "Reviews",
        diffGate: "Diff gate",
        tests: "Tests",
        contracts: "Contract desk",
        policies: "Policies",
        locks: "Locks",
        worktrees: "Worktrees",
      },
    },
    desktop: {
      sectionPrimary: "Core loop",
      sectionAdvanced: "Command deck",
      sectionGovernance: "Desks & controls",
      shellAriaLabel: "OpenVibeCoding command tower desktop shell",
      skipToMainContent: "Skip to main content",
      workspacePickerLabel: "Workspace picker",
      selectWorkspace: "Select workspace",
      loadingPageStyles: "Loading page styles...",
      loadingPage: "Loading page...",
      localeToggleAriaLabel: "Switch to Chinese",
      localeToggleButtonLabel: "中文",
      commandTower: {
        title: "Command Tower",
        subtitle: "OpenVibeCoding on desktop stays focused on execution and operator decisions; deeper governance analysis still moves to the web view.",
        currentModePrefix: "Current mode:",
        badges: {
          liveRefresh: "Live refresh",
          paused: "Paused",
          backoff: "Backoff",
          sloPrefix: "SLO: ",
        },
        actions: {
          refreshProgress: "Refresh progress",
          refreshing: "Refreshing...",
          pauseAutoRefresh: "Pause auto-refresh",
          resumeAutoRefresh: "Resume auto-refresh",
          resumeWork: "Resume work",
          openWebDeepAnalysis: "Open web deep analysis",
          showAdvancedDetail: "Show advanced detail",
          hideAdvancedDetail: "Hide advanced detail",
        },
        collapsedHint: "Advanced operator detail stays collapsed by default so the first screen remains action-focused.",
        webHandoffIntro: "Desktop owns the execution loop: refresh, pause, enter a session, and make operator decisions. For long-list analysis or complex filtering, use the",
        webAnalysisView: "web analysis view",
        metrics: {
          totalSessions: "Total sessions",
          active: "Active",
          failed: "Failed",
          blocked: "Blocked",
        },
        filterTitle: "Filters",
        filterHint: "Filters only affect the session list and can be combined with focus mode.",
        statusLegend: "Status",
        projectKey: "Project key",
        sort: "Sort",
        apply: "Apply",
        reset: "Reset",
        draftNotApplied: "Draft not applied",
        focusLabels: {
          all: "All",
          highRisk: "High risk",
          blocked: "Blocked",
          running: "Running",
        },
        refreshHealth: {
          fullSuccess: "Full refresh succeeded",
          fullFailure: "Full pipeline refresh failed",
          partialSuccess: (okCount) => `Partial refresh succeeded (${okCount}/3)`,
        },
        sectionLabels: {
          overview: "Overview",
          sessions: "Sessions",
          alerts: "Alerts",
          healthy: "Healthy",
          issue: "Issue",
        },
        errorIssueBadge: "Issue",
        errorRecommendedAction: "Recommended action: retry the refresh first. If it keeps failing, inspect network reachability and backend availability.",
        retryRefresh: "Retry refresh",
        retrying: "Retrying...",
        pauseLiveTriage: "Pause live triage",
        noSessionsForFilters: "No sessions match the current filters.",
        noSessionsForFocus: "No sessions match the current focus mode.",
        viewAll: "View all",
        sessionBoardTitle: "Session board",
        sessionBoardCount: (visible, total) => `Showing ${visible} / ${total} sessions`,
        noSessionsYet: "No sessions yet.",
        refreshNow: "Refresh now",
        viewAllSessions: "View all sessions",
        blockingHotspots: "Blocking hotspots",
        drawer: {
          ariaLabel: "Command Tower context drawer",
          title: "Context",
          close: "Close drawer",
          quickActions: "Quick actions",
          health: "Health",
          inspectionPrompts: "Inspection prompts",
          alerts: "Alerts",
          export: "Export",
          copy: "Copy",
          running: "RUNNING",
          paused: "PAUSED",
          focusHits: "Focus hits",
          filterState: "Filter state",
          allFilters: "ALL",
          noAlerts: "System healthy. No alerts right now.",
          reviewAlertState: "Review alert state",
          records: (count) => `${count} records`,
          criticalCount: (count) => `${count} critical`,
        },
      },
      runDetail: {
        backToList: "Back to list",
        taskLabelPrefix: "Task",
        liveModeActive: "LIVE",
        liveModePaused: "PAUSED",
        liveTogglePauseTitle: "Pause live updates",
        liveToggleResumeTitle: "Resume live updates",
        loadErrorPrefix: "Run detail failed to load:",
        loadErrorNextStep: "Next step: retry loading first. If it still fails, return to the list and open the run again.",
        retryLoad: "Retry load",
        noDetailPayload: "No detail payload is available for this run yet.",
        noDetailNextStep: "Next step: retry loading first. If it still fails, return to the list and select the run again.",
        pendingApprovalWithCount: (count) =>
          `This run is waiting for human approval (${count} item(s)). Next step: complete the approval before continuing.`,
        pendingApprovalWithoutCount:
          "This run is marked as awaiting human approval. Next step: complete the approval before continuing.",
        operatorCopilotTitle: "AI operator copilot",
        operatorCopilotIntro:
          "Generate one bounded operator brief grounded in current run, compare, proof, incident, workflow, queue, and approval truth.",
        operatorCopilotButton: "Generate operator brief",
        tabs: {
          events: (count) => `Event timeline (${count})`,
          diff: "Change diff",
          reports: (count) => `Reports (${count})`,
          tools: (count) => `Tool calls (${count})`,
          chain: "Chain flow",
          contract: "Contract policy",
          replay: "Replay compare",
        },
        summaryCards: {
          overviewTitle: "Run overview",
          executionRolesTitle: "Execution roles",
          evidenceTitle: "Evidence and traceability",
        },
        fieldLabels: {
          runId: "Run ID",
          taskId: "Task ID",
          status: "Status",
          executionSemantic: "Execution semantic",
          failureCode: "Failure code",
          failureSummary: "Failure summary",
          nextAction: "Next action",
          currentOwner: "Current owner",
          assignedExecution: "Assigned execution",
          createdAt: "Created at",
          traceId: "Trace ID",
          workflow: "Workflow",
          failureReason: "Failure reason",
          allowedPaths: "Allowed paths",
        },
        tableHeaders: {
          time: "Time",
          event: "Event",
          level: "Level",
          taskId: "Task ID",
          tool: "Tool",
          status: "Status",
          duration: "Duration",
          error: "Error",
        },
        actionBar: {
          promoteEvidence: "Promote evidence",
          rollback: "Rollback",
          reject: "Reject",
          refresh: "Refresh",
        },
        emptyStates: {
          noExecutionRoleStatus: "No execution role status is available yet.",
          executionRolesNextStep: "Next step: use Retry fetch to request a fresh payload.",
          retryFetch: "Retry fetch",
          noEvidenceSummary: "No evidence summary is available yet.",
          evidenceNextStep: "Next step: refresh the payload and try again.",
          refreshData: "Refresh data",
          noEvents: "No events are available yet.",
          eventsNextStep: "Next step: refresh events and request a fresh payload.",
          refreshEvents: "Refresh events",
          noDiff: "No diff content is available yet.",
          diffNextStep: "Next step: retry loading. If it stays empty, return to Event timeline and inspect execution progress there.",
          backToEventTimeline: "Back to Event timeline",
          noReports: "No reports are available yet.",
          reportsNextStep: "Next step: refresh reports and request a fresh payload.",
          refreshReports: "Refresh reports",
          noToolCalls: "No tool-call records are available yet.",
          toolCallsNextStep: "Next step: refresh tool calls and request a fresh payload.",
          refreshToolCalls: "Refresh tool calls",
          noChainFlow: "No chain-flow content is available yet.",
          chainNextStep: "Next step: refresh chain flow and request a fresh payload.",
          refreshChain: "Refresh chain flow",
          chainSpecTitle: "Chain Spec (chain.json)",
          chainReportTitle: "Chain Report",
          noContractSnapshot: "No contract snapshot is available yet.",
          contractNextStep: "Next step: refresh contract data and request a fresh payload.",
          refreshContract: "Refresh contract",
          replayTitle: "Replay compare",
          replayDescription: "Choose a baseline run to compare evidence-chain differences.",
          selectBaselineRun: "Select a baseline run...",
          runReplay: "Run replay",
          replayResult: "Replay result",
          compareDecisionTitle: "Compare decision",
          compareAligned: "The current run looks aligned with the selected baseline.",
          compareNeedsReview: "Compare found at least one delta, so this run still needs operator review.",
          compareNextStep: "Next step: review compare, proof, and incident context before deciding to replay, approve, or keep the run blocked.",
          actionContextTitle: "Action context",
          proofPrefix: "Proof:",
          incidentPrefix: "Incident:",
          noProofIncident: "No proof or incident pack is attached yet. Continue from the reports below.",
          compareSummaryTitle: "Compare summary",
          openCompareSurface: "Open compare surface",
          proofPackTitle: "Proof pack",
          relatedReportsTitle: "Related reports",
          testReportTitle: "test_report.json",
          reviewReportTitle: "review_report.json",
          evidenceReportTitle: "evidence_report.json",
        },
      },
      workflowListPage: {
        title: "Workflow Cases",
        subtitle:
          "Workflow Cases keep queue posture, linked runs, verdict, and later Proof & Replay decisions attached to the same operating record.",
        summaryAriaLabel: "Workflow Case operator summary",
        countsBadge: (workflowCount, queueCount) => `${workflowCount} workflows / ${queueCount} queue items`,
        metricLabels: {
          workflowCases: "Workflow Cases",
          queueSla: "Queue / SLA",
          nextRecommendedAction: "Next recommended action",
        },
        casesWithQueuedWork: (count) => `Cases with queued work: ${count}`,
        eligibleNow: (eligibleCount, atRiskCount) => `Eligible now: ${eligibleCount} / at risk: ${atRiskCount}`,
        recommendedActions: {
          runNext: "Run the next queued task to move the active Workflow Case chain forward.",
          reviewTiming: "Review queue timing and SLA state, then dispatch when the next case becomes eligible.",
          openWorkflow: "Open a Workflow Case and queue the latest run contract to start the next operator loop.",
          createFirstWorkflow: "Create the first Workflow Case from PM intake, then return here to dispatch queued work.",
        },
        emptyTitle: "No workflow cases yet",
        emptyHint: "A Workflow Case is opened automatically on first execution.",
        tableCaption: "Workflow list",
        tableHeaders: {
          workflowId: "Workflow ID",
          status: "Status",
          namespace: "Namespace",
          taskQueue: "Task queue",
          runs: "Runs",
        },
        verdictPrefix: "verdict",
        queueSummary: (count, slaState) => `queue: ${count} / SLA ${slaState}`,
      },
      overview: {
        title: "Command deck overview",
        subtitle:
          "OpenVibeCoding starts with one loop: start the task, watch Command Tower, confirm the Workflow Case, then verify Proof & Replay. Only open approvals when the flow asks for one.",
        refreshData: "Refresh data",
        metricsAriaLabel: "Overview metrics",
        metricLabels: {
          totalSessions: "Total sessions",
          activeNow: "Active now",
          failureRatio: "Failure ratio",
          blockedQueue: "Blocked queue",
        },
        primaryActionsTitle: "Primary actions",
        optionalStepLabel: "Optional step",
        approvalCheckpoint: "Approval checkpoint",
        approvalCheckpointDesc:
          "Use the approval workspace only when the flow pauses for human confirmation.",
        currentProgressTitle: "Current progress",
        progressCards: {
          runningNow: "Running now",
          runningNowHint: 'Open "Runs" to follow the active work.',
          runningNowEmpty: "No tasks are running right now. Start a new one from the PM entrypoint.",
          needsAttention: "Needs attention",
          needsAttentionHint:
            "Prioritize the affected Run detail and decide whether to rollback, reject, or replay.",
          needsAttentionEmpty: "No failed tasks are currently visible.",
          riskEvents: "Risk events",
          riskEventsHint: "Inspect the event stream to locate the blocking root cause.",
          riskEventsEmpty: "Recent events do not show warning signals.",
        },
        recentRunsTitle: "Recent runs",
        recentRunsHint: "Open Run detail from here to review evidence and resolve outcomes.",
        noRunsYet: "No runs yet. Start your first request from the PM entrypoint.",
        viewAllRuns: "View all runs",
        recentEventsTitle: "Recent exceptions",
        viewAllExceptions: "View all exceptions",
        noExceptionsYet:
          "No exception signals yet. Failed runs and risk events will appear here after tasks start running.",
        openEventStream: "Open event stream",
        viewRun: "View Run",
        runningNowTitle: "Running now",
        recentExceptionTaskRequiresAttention: (taskId) => `Task ${taskId} requires attention`,
        recentExceptionOperatorEventFallback: "Operator event",
        recentExceptionLevelPrefix: "Level",
        recentExceptionRunPrefix: "Run",
        tableHeaders: {
          runId: "Run ID",
          taskId: "Task ID",
          status: "Status",
          createdAt: "Created at",
          time: "Time",
          exception: "Exception",
          details: "Details",
          action: "Action",
        },
        quickActions: {
          step1Label: "Step 1 · Brief PM",
          step1Desc:
            "Start at the PM entrypoint, state the goal and acceptance criteria, and let the system open the session.",
          step2Label: "Step 2 · Watch progress",
          step2Desc: "Use Command Tower to monitor session state, alerts, and pipeline health.",
          step3Label: "Step 3 · Review Workflow Cases",
          step3Desc:
            "Open Workflow Cases to confirm queue posture, operating verdict, and the current case record.",
          step4Label: "Step 4 · Verify Proof & Replay",
          step4Desc: "Open runs to inspect status, evidence chain, compare state, and replay results.",
        },
      },
      approval: {
        pageTitle: "Quick approval",
        pageSubtitle: "Manual approval queue for critical runs that are blocked pending human confirmation.",
        refresh: "Refresh",
        warningBanner: "This surface separates pending approvals, queue load failure, and manual approval input. A quiet queue is not proof that approval is globally unnecessary.",
        queueTitle: "Approval Queue",
        pendingBadge: (count) => `${count} pending`,
        criticalBadge: "CRITICAL",
        noPendingText: "No runs are waiting for approval in the current queue. This is not evidence that approval is disabled or unnecessary everywhere.",
        summaryLabel: "Summary",
        taskIdLabel: "Task ID",
        failureReasonLabel: "Failure reason",
        approveExecution: "Approve execution",
        manualInputTitle: "Manual Approval Input",
        manualInputHint: "Enter a Run ID to approve a task that is not currently listed in the queue",
        runIdLabel: "Run ID",
        runIdPlaceholder: "Enter Run ID",
        approve: "Approve",
        confirmDialogAriaLabel: "Approval confirmation dialog",
        closeConfirmDialogAriaLabel: "Close approval confirmation dialog",
        confirmTitle: "Confirm approval",
        confirmDescription: (runId) => `Approve run ${runId}? This action cannot be undone.`,
        cancel: "Cancel",
        confirmApproval: "Confirm approval",
        approvedToast: (runId) => `Approved ${runId}`,
      },
      labels: {
        overview: "Overview",
        pmIntake: "PM intake",
        commandTower: "Command Tower",
        runs: "Proof & Replay",
        runDetail: "Proof room",
        runCompare: "Run Compare",
        workflowCases: "Workflow Cases",
        workflowCaseDetail: "Workflow Case Detail",
        quickApproval: "Quick approval",
        search: "Search",
        events: "Events",
        contracts: "Contract desk",
        reviews: "Reviews",
        tests: "Tests",
        policies: "Policies",
        agents: "Role desk",
        locks: "Locks",
        worktrees: "Worktrees",
        diffGate: "Diff gate",
        sessionView: "Session View",
      },
    },
  },
  "zh-CN": {
    brandTitle: "OpenVibeCoding",
    brandSubtitle: "规划 · 派工 · 追踪 · 续跑 · 验真",
    dashboard: {
      homePhase2: {
        heroTitle: "面向 AI 工程的开放指挥塔",
        heroSubtitle:
          "别再盯着 AI coding 一步一步催了。AI coding 不缺模型，缺的是指挥塔。OpenVibeCoding 会围绕 Codex / Claude Code 去规划、派工、追踪、续跑和验真，把长期工程任务收进一条可治理、可续跑、可验真的操作路径。",
        startFirstTaskLabel: "启动首个任务",
        startNewTaskLabel: "启动新任务",
        viewLatestRunsLabel: "查看最近 runs",
        investigateHighRiskFailuresLabel: "排查高风险失败",
        handleLatestFailureLabel: "处理最近失败",
        productSpineTitle: "一个开放指挥塔，五个动作",
        productSpineDescription:
          "首页先讲 live command deck，再把主循环钉在三块真相面上：Command Tower、Workflow Cases 和 Proof & Replay。",
        productSpineCards: [
          {
            href: "/command-tower",
            title: "Command Tower",
            desc: "在一个操作面里观察受治理的 AI agent 和 MCP 驱动工作如何前进。",
          },
          {
            href: "/workflows",
            title: "Workflow Cases",
            desc: "把请求、队列、判定、证明和关联 runs 绑定到同一个案例记录里。",
          },
          {
            href: "/runs",
            title: "Proof & Replay",
            desc: "在真正信任结果前，先检查证据包、对比重跑和失败回放。",
          },
        ],
        publicTemplatesTitle: "一个已证明工作流，两个展示扩展",
        publicTemplatesDescription:
          "先从 `news_digest` 开始。它是官方公开基线。`topic_brief` 和 `page_brief` 仍然有用，但在拿到各自健康证明包之前，它们仍属于展示路径。",
        publicTemplatesActionLabel: "打开证明包",
        publicTemplatesActionHref: "/use-cases/",
        publicTemplateCards: [
          {
            href: "/pm?template=news_digest",
            badge: "已发布验证的首跑",
            title: "news_digest",
            desc: "围绕一个主题生成新闻摘要，同时保留可审计的证据链。",
            bestFor: "适合最快证明导向的公开路径。",
            example: "Seattle tech and AI + 3 个来源域名 + 24h",
            proof: "Proof 状态：官方公开基线",
            fields: ["topic", "sources[]", "time_range", "max_results"],
          },
          {
            href: "/pm?template=topic_brief",
            badge: "公开展示",
            title: "topic_brief",
            desc: "把一个有边界的话题简报做成只读 workflow case，并附带搜索证据。",
            bestFor: "适合围绕一个主题和最近时间窗做窄范围简报。",
            example: "Seattle tech and AI + 7d + 5 results",
            proof: "Proof 状态：公开，但尚未作为发布级基线",
            fields: ["topic", "time_range", "max_results"],
          },
          {
            href: "/pm?template=page_brief",
            badge: "公开展示",
            title: "page_brief",
            desc: "围绕单个 URL 和浏览器证据生成只读 workflow case。",
            bestFor: "适合单页比整段主题更重要的情况。",
            example: "https://example.com + focused summary request",
            proof: "Proof 状态：浏览器证据展示路径",
            fields: ["url", "focus"],
          },
        ],
        publicAdvantagesTitle: "指挥塔背后的三层工程能力",
        publicAdvantagesDescription:
          "Prompt 5 把公开叙事继续锚定在 proof、replay、只读 MCP 访问和可解释的 operator review，而不是泛泛 AI 口号。",
        publicAdvantageCards: [
          {
            href: "/runs",
            title: "先有证明，再谈推进",
            desc: "每个首跑 case 都会先落到 evidence、compare 和 replay，再谈是否可信。",
          },
          {
            href: "/runs",
            title: "AI operator 摘要",
            desc: "Run Detail 和 Run Compare 已经能解释变化点、影响，以及下一步 operator 动作。",
          },
          {
            href: "/workflows",
            title: "可分享的 Workflow Cases",
            desc: "Workflow Cases 正在变成可复用资产，而不是只停留在一次性详情页里。",
          },
        ],
        ecosystemTitle: "与当前 coding-agent 生态的关系",
        ecosystemDescription:
          "前门继续以 Codex、Claude Code 和只读 MCP 为主轴。OpenHands 和 comparison-only 工具只放在生态层，不放进 hero。",
        ecosystemAction: "打开生态地图",
        ecosystemActionHref: "/ecosystem/",
        ecosystemCards: [
          {
            badge: "主工作流绑定",
            title: "Codex 工作流",
            desc: "当 Codex 驱动的工作需要统一指挥塔、案例记录和可回放证明路径时，就该由 OpenVibeCoding 承接。",
            href: "/command-tower",
            prefetch: true,
          },
          {
            badge: "主工作流绑定",
            title: "Claude Code 工作流",
            desc: "同一套操作面也适用于 Claude Code 风格的编码循环，重点在于治理可见性、审批和证据。",
            href: "/command-tower",
            prefetch: true,
          },
          {
            badge: "协议层",
            title: "只读 MCP",
            desc: "这里的 MCP 是真实协议面，但当前边界仍然是只读。外部工具可以读取真相，不能修改真相。",
            href: "/runs",
            prefetch: true,
          },
          {
            badge: "相邻生态",
            title: "OpenHands 与 comparison 层",
            desc: "OpenHands 留在更广的生态层；OpenCode 维持 comparison-only，OpenClaw 继续不进主前门。",
            href: "/ecosystem/",
          },
        ],
        integrationTitle: "选择正确的采用路径",
        integrationDescription:
          "先把 compatibility matrix 当成主路由，把 proof-first 指南当成最快建立信任的入口，再在任务真正明确后进入协议、playbook、package 或 AI 页面。",
        proofFirstActionLabel: "查看首个已证明工作流",
        proofFirstActionHref: "/use-cases/",
        integrationCards: [
          {
            badge: "决策入口",
            title: "Compatibility matrix",
            desc: "如果你想先用一页看懂 Codex、Claude Code、OpenClaw、只读 MCP、skills 和 builder 入口的关系，就从这里开始。",
            href: "/compatibility/",
          },
          {
            badge: "真实采用地图",
            title: "Integration guide",
            desc: "如果你需要更深入地理解 Codex、Claude Code 和 OpenClaw 的定位边界，而不是只看路由摘要，就看这里。",
            href: "/integrations/",
          },
          {
            badge: "Repo-owned playbook",
            title: "Skills quickstart",
            desc: "如果你的团队需要可复用的 agent playbook，而不是自己从 `.agents/skills/` 猜规则，就从这里开始。",
            href: "/skills/",
          },
        ],
        aiSurfacesTitle: "AI 功能已经进入主工作流",
        aiSurfacesDescription:
          "OpenVibeCoding 里的 AI 不是漂浮聊天框。它已经分别出现在执行前建议、工作流解释，以及运行/对比的操作摘要里。",
        aiSurfacesActionLabel: "打开 AI + MCP + API 页面",
        aiSurfacesActionHref: "/ai-surfaces/",
        aiSurfaceCards: [
          {
            badge: "执行前建议",
            title: "Flight Plan 副驾驶",
            desc: "PM intake 现在可以在执行前先生成一份有边界的建议摘要，让审批和证据预期更早可见。",
            href: "/pm",
            prefetch: true,
          },
          {
            badge: "工作流级 AI",
            title: "Workflow 副驾驶",
            desc: "Workflow Case 已经能给出工作流级别的解释，覆盖队列姿态、最新 run 上下文和下一步操作。",
            href: "/workflows",
            prefetch: true,
          },
          {
            badge: "运行时 AI",
            title: "Run / Compare 操作摘要",
            desc: "Run Detail 和 compare 面已经能解释差异、证明、incident 上下文和下一步动作，而不假装自己在执行恢复。",
            href: "/runs",
            prefetch: true,
          },
        ],
        builderTitle: "Builder 入口",
        builderDescription:
          "这还不是完整 SDK 平台，但 builder 入口现在已经同时覆盖 read-only MCP quickstart、API and contract quickstart，以及 package 级 client/shared surface。",
        builderQuickstartCtaLabel: "打开 builder 快速入口",
        builderQuickstartCtaHref: "/builders/",
        builderCards: [
          {
            badge: "协议快速入口",
            title: "Read-only MCP quickstart",
            desc: "如果你想先拿到一张最短、最真实的 MCP 地图，再回头看 package 细节，就从这里开始。",
            href: "/mcp/",
          },
          {
            badge: "API 快速入口",
            title: "API and contract quickstart",
            desc: "如果你想先看 OpenAPI、contract-facing types 和 thin client 入口，再决定接哪一层，就从这里开始。",
            href: "/api/",
          },
          {
            badge: "薄客户端",
            title: "@cortexpilot/frontend-api-client",
            desc: "当你想从一个导入边界里拿到 runs、Workflow Cases、approvals 和 Command Tower 读取能力时，就从这里开始。",
            href: "https://github.com/xiaojiou176-open/OpenVibeCoding/blob/main/packages/frontend-api-client/README.md",
          },
          {
            badge: "契约层",
            title: "@cortexpilot/frontend-api-contract",
            desc: "如果你想先看生成契约边界的人类说明，再决定要不要打开原始类型文件，就先从这个 README 开始。",
            href: "https://github.com/xiaojiou176-open/OpenVibeCoding/blob/main/packages/frontend-api-contract/docs/README.md",
          },
          {
            badge: "表现层 substrate",
            title: "@cortexpilot/frontend-shared",
            desc: "品牌 copy、locale helper、status presentation 和 frontend-only types 已经集中到这一层，而不是散落在各 app 里。",
            href: "https://github.com/xiaojiou176-open/OpenVibeCoding/blob/main/packages/frontend-shared/README.md",
          },
        ],
        liveCaseGalleryTitle: "真实 Workflow Case 画廊",
        liveCaseGalleryDescription:
          "把真实 Workflow Cases 作为轻量 showcase asset 来使用。这里会直接链接 live case detail 和可分享 recap，而不是伪造 demo-only 画廊数据。",
        liveCaseGalleryActionLabel: "打开 Workflow Cases",
        liveCaseGalleryActionHref: "/workflows",
        firstTaskGuideTitle: "首个任务指南（可展开）",
        firstTaskGuideDescription:
          "从请求开始，观察 Command Tower，确认 Workflow Case，再检查 Proof & Replay。默认折叠，避免首屏过吵。",
        firstTaskGuideSummary: "显示四步首跑流程",
        firstTaskGuideSteps: [
          {
            href: "/pm",
            prefetch: true,
            step: "第 1 步",
            title: "描述请求（目标 + 验收）",
            desc: "用一句话说清楚目标和验收标准，然后让系统打开 session。",
          },
          {
            href: "/command-tower",
            prefetch: false,
            step: "第 2 步",
            title: "观察实时进展（确认它在前进）",
            desc: "打开 Command Tower，确认 run 在推进而不是卡住。",
          },
          {
            href: "/workflows",
            prefetch: true,
            step: "第 3 步",
            title: "确认 Workflow Case",
            desc: "打开 Workflow Cases，确认持久案例记录、队列姿态和关联 runs。",
          },
          {
            href: "/runs",
            prefetch: true,
            step: "第 4 步",
            title: "检查 Proof & Replay",
            desc: "打开 run 台账，检查状态、证据、compare 状态和 replay 状态。",
          },
        ],
        optionalApprovalStep: {
          href: "/god-mode",
          prefetch: true,
          step: "可选",
          title: "审批检查点（仅在需要 review 时）",
          desc: "用 Quick approval 确认被阻塞步骤，并完成最后放行。",
        },
      },
      skipToMainContent: "跳到控制台主内容",
      navigationAriaLabel: "控制台导航",
      topbarTitle: "AI 工程指挥塔",
      platformStatusAriaLabel: "平台状态概览",
      lowFrequencyToolsLabel: "低频工具",
      localeToggleAriaLabel: "切换到英文",
      localeToggleButtonLabel: "EN",
      badges: {
        governanceView: "治理视图",
        liveVerificationRequired: "需要实时核验",
        pageLevelStatus: "页面级状态",
      },
      approval: {
        pageTitle: "人工审批",
        pageSubtitle: "在恢复执行前，把所有 HUMAN_APPROVAL_REQUIRED 项集中审阅一遍。",
        panelTitle: "人工裁决",
        panelIntro: "人工裁决页会把待审批项、只读权限缺口和队列拉取失败分开显示。队列安静，不代表全局不再需要审批。",
        roleConfigurationAriaLabel: "审批角色配置",
        operatorRoleLabel: "操作角色",
        operatorRoleUnconfigured: "未配置",
        refreshPending: "刷新待审批队列",
        refreshingPending: "刷新中...",
        lastSuccessfulRefreshPrefix: "最近一次成功刷新：",
        actionsDisabledTitle: "当前审批操作为只读。",
        queueLoadingBadge: "刷新中",
        queueLoadFailedBadge: "加载失败",
        queueIdleBadge: "没有待处理项",
        queuePendingBadge: (count) => `${count} 条待审批`,
        pendingTruthUnavailable: (error) => `待审批真相暂不可用：${error}`,
        recoveryTip: "恢复建议：先确认登录状态和审批角色，再进行重试。",
        lastAttemptPrefix: "最近一次尝试：",
        retryFetch: "重试拉取",
        retryingFetch: "重试中...",
        inspectConnection: "打开 PM 会话检查连接",
        verifyAuthState: "打开指挥塔检查认证状态",
        loadingPending: "正在加载待审批队列...",
        pendingQueueAriaLabel: "待审批队列",
        reasonLabel: "原因",
        requiredActionLabel: "需要动作",
        resumeAtLabel: "恢复位置",
        continueButton: "我已确认，继续执行",
        continuingButton: "审批中...",
        manualHint: "当事件流出现 HUMAN_APPROVAL_REQUIRED 时，把 run_id 粘贴到这里后批准。该动作会被写入事件日志。",
        runIdLabel: "运行 ID",
        runIdPlaceholder: "粘贴 run_id...",
        approveButton: "批准",
        approvingButton: "审批中...",
        confirmTitle: "确认批准",
        confirmDescription: (runId) => `批准 ${runId} 并继续执行吗？该操作会写入事件日志，且不可撤销。`,
        cancel: "取消",
        confirmApproval: "确认批准",
        statusRefreshingQueue: "正在刷新待审批队列...",
        statusRetryingQueue: "正在重试待审批队列...",
        statusQueueRefreshed: (count) => `待审批队列已刷新。当前 ${count} 条。`,
        statusRefreshFailed: (message, authError) => authError
            ? `待审批队列刷新失败：${message}。请先确认权限或重新登录后再试。`
            : "待审批队列刷新失败。请先处理错误再重试。",
        statusRetryFailed: (message, authError) => authError
            ? `重试失败：${message}。请先确认权限或重新登录后再试。`
            : `重试失败：${message}。`,
        statusEnterRunId: "请先输入 run_id 再批准。",
        statusSubmittingApproval: "正在提交审批...",
        statusApproved: "已批准。",
        statusFailed: (message) => `失败：${message}`,
      },
      sectionPrimary: "核心主线",
      sectionAdvanced: "指挥面",
      labels: {
        overview: "总览",
        pmIntake: "PM 入口",
        commandTower: "指挥塔",
        runs: "Proof & Replay",
        quickApproval: "快速审批",
        search: "检索",
        agents: "角色桌",
        workflowCases: "工作流案例",
        events: "事件流",
        reviews: "评审",
        diffGate: "差异门禁",
        tests: "测试",
        contracts: "合约桌",
        policies: "策略",
        locks: "锁管理",
        worktrees: "工作树",
      },
    },
    desktop: {
      sectionPrimary: "核心主线",
      sectionAdvanced: "指挥面",
      sectionGovernance: "桌面与控制",
      shellAriaLabel: "OpenVibeCoding 指挥塔桌面端",
      skipToMainContent: "跳到主内容",
      workspacePickerLabel: "工作区切换器",
      selectWorkspace: "选择工作区",
      loadingPageStyles: "正在加载页面样式...",
      loadingPage: "正在加载页面...",
      localeToggleAriaLabel: "切换到英文",
      localeToggleButtonLabel: "EN",
      commandTower: {
        title: "指挥塔",
        subtitle: "桌面端聚焦执行与操作决策；更深的治理分析留给 Web 视图。",
        currentModePrefix: "当前模式：",
        badges: {
          liveRefresh: "实时刷新",
          paused: "已暂停",
          backoff: "退避中",
          sloPrefix: "SLO：",
        },
        actions: {
          refreshProgress: "更新进展",
          refreshing: "刷新中...",
          pauseAutoRefresh: "暂停自动刷新",
          resumeAutoRefresh: "恢复自动刷新",
          resumeWork: "继续处理",
          openWebDeepAnalysis: "打开 Web 深度分析",
          showAdvancedDetail: "展开专家信息",
          hideAdvancedDetail: "收起专家信息",
        },
        collapsedHint: "默认先收起高级操作细节，让第一屏保持执行优先。",
        webHandoffIntro: "桌面端负责执行主循环：刷新、暂停、进入会话并作出操作决策。若要做长列表分析或复杂筛选，请使用",
        webAnalysisView: "Web 分析视图",
        metrics: {
          totalSessions: "会话总数",
          active: "活跃",
          failed: "失败",
          blocked: "阻塞",
        },
        filterTitle: "筛选器",
        filterHint: "筛选器只影响会话列表，可与 focus mode 组合使用。",
        statusLegend: "状态",
        projectKey: "项目键",
        sort: "排序",
        apply: "应用",
        reset: "重置",
        draftNotApplied: "草稿未应用",
        focusLabels: {
          all: "全部",
          highRisk: "高风险",
          blocked: "阻塞",
          running: "运行中",
        },
        refreshHealth: {
          fullSuccess: "完整刷新成功",
          fullFailure: "整条刷新链路失败",
          partialSuccess: (okCount) => `部分刷新成功（${okCount}/3）`,
        },
        sectionLabels: {
          overview: "总览",
          sessions: "会话",
          alerts: "告警",
          healthy: "健康",
          issue: "异常",
        },
        errorIssueBadge: "问题",
        errorRecommendedAction: "建议动作：先重试刷新。如果仍然失败，再检查网络连通性和后端可用性。",
        retryRefresh: "重试刷新",
        retrying: "重试中...",
        pauseLiveTriage: "暂停实时排查",
        noSessionsForFilters: "当前筛选条件下没有匹配的会话。",
        noSessionsForFocus: "当前 focus 模式下没有匹配的会话。",
        viewAll: "查看全部",
        sessionBoardTitle: "会话面板",
        sessionBoardCount: (visible, total) => `显示 ${visible} / ${total} 个会话`,
        noSessionsYet: "还没有会话。",
        refreshNow: "立即刷新",
        viewAllSessions: "查看全部会话",
        blockingHotspots: "阻塞热点",
        drawer: {
          ariaLabel: "指挥塔上下文抽屉",
          title: "上下文",
          close: "关闭抽屉",
          quickActions: "快捷动作",
          health: "健康状态",
          inspectionPrompts: "排查提示",
          alerts: "告警",
          export: "导出",
          copy: "复制",
          running: "运行中",
          paused: "已暂停",
          focusHits: "焦点命中",
          filterState: "筛选状态",
          allFilters: "全部",
          noAlerts: "系统当前健康，没有告警。",
          reviewAlertState: "查看告警状态",
          records: (count) => `${count} 条记录`,
          criticalCount: (count) => `${count} 个严重`,
        },
      },
      runDetail: {
        backToList: "返回列表",
        taskLabelPrefix: "任务",
        liveModeActive: "运行中",
        liveModePaused: "已暂停",
        liveTogglePauseTitle: "暂停实时更新",
        liveToggleResumeTitle: "恢复实时更新",
        loadErrorPrefix: "Run 详情加载失败：",
        loadErrorNextStep: "下一步：先重试加载。如果仍然失败，就回到列表重新打开这个 Run。",
        retryLoad: "重试加载",
        noDetailPayload: "当前还没有这个 Run 的详情负载。",
        noDetailNextStep: "下一步：先重试加载。如果仍然失败，就回到列表重新选择这个 Run。",
        pendingApprovalWithCount: (count) =>
          `这个 Run 正在等待人工审批（${count} 项）。下一步：先完成审批再继续。`,
        pendingApprovalWithoutCount:
          "这个 Run 被标记为等待人工审批。下一步：先完成审批再继续。",
        operatorCopilotTitle: "AI 操作员副驾驶",
        operatorCopilotIntro:
          "生成一份有边界的操作员摘要，基于当前 run、compare、proof、incident、workflow、queue 和 approval 真相。",
        operatorCopilotButton: "生成操作摘要",
        tabs: {
          events: (count) => `事件时间线（${count}）`,
          diff: "变更差异",
          reports: (count) => `报告（${count}）`,
          tools: (count) => `工具调用（${count}）`,
          chain: "链路流转",
          contract: "合约策略",
          replay: "回放对比",
        },
        summaryCards: {
          overviewTitle: "Run 总览",
          executionRolesTitle: "执行角色",
          evidenceTitle: "证据与可追溯性",
        },
        fieldLabels: {
          runId: "Run ID",
          taskId: "任务 ID",
          status: "状态",
          executionSemantic: "执行语义",
          failureCode: "失败代码",
          failureSummary: "失败摘要",
          nextAction: "下一步动作",
          currentOwner: "当前负责人",
          assignedExecution: "当前执行分配",
          createdAt: "创建时间",
          traceId: "追踪 ID",
          workflow: "工作流",
          failureReason: "失败原因",
          allowedPaths: "允许路径",
        },
        tableHeaders: {
          time: "时间",
          event: "事件",
          level: "级别",
          taskId: "任务 ID",
          tool: "工具",
          status: "状态",
          duration: "耗时",
          error: "错误",
        },
        actionBar: {
          promoteEvidence: "提升为证据",
          rollback: "回滚",
          reject: "拒绝",
          refresh: "刷新",
        },
        emptyStates: {
          noExecutionRoleStatus: "当前还没有执行角色状态。",
          executionRolesNextStep: "下一步：点击“重试拉取”，请求一份新的负载。",
          retryFetch: "重试拉取",
          noEvidenceSummary: "当前还没有证据摘要。",
          evidenceNextStep: "下一步：刷新负载后再试一次。",
          refreshData: "刷新数据",
          noEvents: "当前还没有事件记录。",
          eventsNextStep: "下一步：刷新事件，并请求一份新的负载。",
          refreshEvents: "刷新事件",
          noDiff: "当前还没有差异内容。",
          diffNextStep: "下一步：先重试加载。如果仍然为空，就回到事件时间线继续看执行进展。",
          backToEventTimeline: "返回事件时间线",
          noReports: "当前还没有报告。",
          reportsNextStep: "下一步：刷新报告，并请求一份新的负载。",
          refreshReports: "刷新报告",
          noToolCalls: "当前还没有工具调用记录。",
          toolCallsNextStep: "下一步：刷新工具调用，并请求一份新的负载。",
          refreshToolCalls: "刷新工具调用",
          noChainFlow: "当前还没有链路流转内容。",
          chainNextStep: "下一步：刷新链路流转，并请求一份新的负载。",
          refreshChain: "刷新链路流转",
          chainSpecTitle: "链路规格（chain.json）",
          chainReportTitle: "链路报告",
          noContractSnapshot: "当前还没有合约快照。",
          contractNextStep: "下一步：刷新合约数据，并请求一份新的负载。",
          refreshContract: "刷新合约",
          replayTitle: "回放对比",
          replayDescription: "选择一个基线 run，比较证据链差异。",
          selectBaselineRun: "选择一个基线 run...",
          runReplay: "运行回放",
          replayResult: "回放结果",
          compareDecisionTitle: "对比结论",
          compareAligned: "当前 run 与所选基线看起来是一致的。",
          compareNeedsReview: "对比发现至少一个 delta，所以这个 run 仍然需要操作员复核。",
          compareNextStep: "下一步：先检查 compare、proof 和 incident 上下文，再决定是回放、批准还是继续阻塞。",
          actionContextTitle: "动作上下文",
          proofPrefix: "Proof：",
          incidentPrefix: "Incident：",
          noProofIncident: "当前没有附带 proof 或 incident pack。先从下面的报告继续排查。",
          compareSummaryTitle: "对比摘要",
          openCompareSurface: "打开对比视图",
          proofPackTitle: "Proof 包",
          relatedReportsTitle: "相关报告",
          testReportTitle: "test_report.json",
          reviewReportTitle: "review_report.json",
          evidenceReportTitle: "evidence_report.json",
        },
      },
      workflowListPage: {
        title: "工作流案例",
        subtitle:
          "工作流案例会把队列姿态、关联 Runs、结论，以及后续的 Proof & Replay 决策都绑在同一条操作记录上。",
        summaryAriaLabel: "工作流案例操作摘要",
        countsBadge: (workflowCount, queueCount) => `${workflowCount} 个工作流 / ${queueCount} 个队列项`,
        metricLabels: {
          workflowCases: "工作流案例",
          queueSla: "队列 / SLA",
          nextRecommendedAction: "下一步建议动作",
        },
        casesWithQueuedWork: (count) => `已有排队工作的案例：${count}`,
        eligibleNow: (eligibleCount, atRiskCount) => `当前可执行：${eligibleCount} / 有风险：${atRiskCount}`,
        recommendedActions: {
          runNext: "直接运行下一条排队任务，把当前工作流案例链继续往前推进。",
          reviewTiming: "先检查队列时机和 SLA 状态，等下一条案例变成可执行后再派发。",
          openWorkflow: "先打开一个工作流案例，再把最新 Run 合约排进队列，启动下一轮操作闭环。",
          createFirstWorkflow: "先从 PM intake 创建第一条工作流案例，然后再回到这里派发排队工作。",
        },
        emptyTitle: "当前还没有工作流案例",
        emptyHint: "第一次执行时会自动创建工作流案例。",
        tableCaption: "工作流列表",
        tableHeaders: {
          workflowId: "工作流 ID",
          status: "状态",
          namespace: "命名空间",
          taskQueue: "任务队列",
          runs: "Runs",
        },
        verdictPrefix: "结论",
        queueSummary: (count, slaState) => `队列：${count} / SLA ${slaState}`,
      },
      overview: {
        title: "指挥面总览",
        subtitle:
          "OpenVibeCoding 的第一条主循环是：发起任务、观察指挥塔、确认 Workflow Case、再检查 Proof & Replay。只有在流程要求时才进入审批。",
        refreshData: "刷新数据",
        metricsAriaLabel: "总览指标",
        metricLabels: {
          totalSessions: "会话总数",
          activeNow: "当前活跃",
          failureRatio: "失败占比",
          blockedQueue: "阻塞队列",
        },
        primaryActionsTitle: "主步骤",
        optionalStepLabel: "可选步骤",
        approvalCheckpoint: "审批确认",
        approvalCheckpointDesc: "只有流程暂停并等待人工确认时，才进入审批工作区。",
        currentProgressTitle: "当前进展",
        progressCards: {
          runningNow: "运行中",
          runningNowHint: "打开“运行记录”追踪当前活跃工作。",
          runningNowEmpty: "当前没有正在运行的任务。先从 PM 入口发起一个新的请求。",
          needsAttention: "需要关注",
          needsAttentionHint: "优先打开对应 Run 详情，判断是回滚、拒绝还是重放。",
          needsAttentionEmpty: "当前没有失败任务。",
          riskEvents: "风险事件",
          riskEventsHint: "打开事件流定位阻塞根因。",
          riskEventsEmpty: "最近没有明显的风险信号。",
        },
        recentRunsTitle: "最近运行",
        recentRunsHint: "从这里进入 Run 详情，查看证据并处理结果。",
        noRunsYet: "还没有运行记录。先从 PM 入口发起你的第一个请求。",
        viewAllRuns: "查看全部运行",
        recentEventsTitle: "最近异常",
        viewAllExceptions: "查看全部异常",
        noExceptionsYet: "还没有异常信号。失败任务和风险事件会在任务运行后出现在这里。",
        openEventStream: "打开事件流",
        viewRun: "查看 Run",
        runningNowTitle: "运行中",
        recentExceptionTaskRequiresAttention: (taskId) => `任务 ${taskId} 需要关注`,
        recentExceptionOperatorEventFallback: "操作事件",
        recentExceptionLevelPrefix: "级别",
        recentExceptionRunPrefix: "Run",
        tableHeaders: {
          runId: "Run ID",
          taskId: "Task ID",
          status: "状态",
          createdAt: "创建时间",
          time: "时间",
          exception: "异常",
          details: "详情",
          action: "操作",
        },
        quickActions: {
          step1Label: "主步骤 1 · 发需求",
          step1Desc: "从 PM 入口开始，说明目标和验收标准，让系统先建立会话。",
          step2Label: "主步骤 2 · 看进度",
          step2Desc: "通过 Command Tower 观察会话状态、告警和执行进度。",
          step3Label: "主步骤 3 · 看案例",
          step3Desc: "打开 Workflow Cases，确认队列姿态、运行结论和当前案例记录。",
          step4Label: "主步骤 4 · 核证据",
          step4Desc: "打开运行记录，核对状态、证据链、对比结果和回放信息。",
        },
      },
      approval: {
        pageTitle: "快速审批",
        pageSubtitle: "处理那些因为等待人工确认而阻塞的关键运行。",
        refresh: "刷新",
        warningBanner: "这个界面会把待审批队列、队列拉取失败、以及手动批准输入分开显示。队列安静，不代表全局不需要审批。",
        queueTitle: "审批队列",
        pendingBadge: (count) => `${count} 条待处理`,
        criticalBadge: "关键",
        noPendingText: "当前队列里没有等待审批的运行。这并不代表别的路径上也不再需要审批。",
        summaryLabel: "摘要",
        taskIdLabel: "任务 ID",
        failureReasonLabel: "失败原因",
        approveExecution: "批准执行",
        manualInputTitle: "手动审批输入",
        manualInputHint: "输入一个 Run ID，批准当前不在列表里的任务",
        runIdLabel: "运行 ID",
        runIdPlaceholder: "输入 Run ID",
        approve: "批准",
        confirmDialogAriaLabel: "审批确认弹窗",
        closeConfirmDialogAriaLabel: "关闭审批确认弹窗",
        confirmTitle: "确认批准",
        confirmDescription: (runId) => `批准运行 ${runId} 吗？该操作不可撤销。`,
        cancel: "取消",
        confirmApproval: "确认批准",
        approvedToast: (runId) => `已批准 ${runId}`,
      },
      labels: {
        overview: "总览",
        pmIntake: "PM 入口",
        commandTower: "指挥塔",
        runs: "Proof & Replay",
        runDetail: "证明室",
        runCompare: "运行对比",
        workflowCases: "工作流案例",
        workflowCaseDetail: "工作流案例详情",
        quickApproval: "快速审批",
        search: "检索",
        events: "事件流",
        contracts: "合约桌",
        reviews: "评审",
        tests: "测试",
        policies: "策略",
        agents: "角色桌",
        locks: "锁管理",
        worktrees: "工作树",
        diffGate: "差异门禁",
        sessionView: "会话视图",
      },
    },
  },
};

function normalizeLocale(locale) {
  return locale === "zh-CN" ? "zh-CN" : "en";
}

export function getUiCopy(locale = DEFAULT_UI_LOCALE) {
  return UI_COPY[normalizeLocale(locale)];
}
