#!/usr/bin/env bash

run_ci_step89_ui_truth_gate() {
  echo "🚀 [STEP 8.9/12] Start: UI E2E truth gate (strict)"
  UI_TRUTH_STRICT_MODE="${OPENVIBECODING_CI_UI_TRUTH_GATE_STRICT:-1}"
  UI_TRUTH_DISABLE_AUTO_LATEST_MODE="${OPENVIBECODING_CI_UI_TRUTH_DISABLE_AUTO_LATEST:-1}"
  UI_TRUTH_REQUIRE_RUN_ID_MATCH_MODE="${OPENVIBECODING_CI_UI_TRUTH_REQUIRE_RUN_ID_MATCH:-1}"
  if [ "$UI_TRUTH_STRICT_MODE" != "1" ] && [ "$UI_STRICT_BREAK_GLASS_ACTIVE" != "1" ]; then
    echo "❌ [ci] OPENVIBECODING_CI_UI_TRUTH_GATE_STRICT!=1 is blocked (fail-closed)."
    exit 1
  fi
  if [ "$UI_TRUTH_DISABLE_AUTO_LATEST_MODE" != "1" ] && [ "$UI_STRICT_BREAK_GLASS_ACTIVE" != "1" ]; then
    echo "❌ [ci] OPENVIBECODING_CI_UI_TRUTH_DISABLE_AUTO_LATEST!=1 is blocked (fail-closed)."
    exit 1
  fi
  if [ "$UI_TRUTH_REQUIRE_RUN_ID_MATCH_MODE" != "1" ] && [ "$UI_STRICT_BREAK_GLASS_ACTIVE" != "1" ]; then
    echo "❌ [ci] OPENVIBECODING_CI_UI_TRUTH_REQUIRE_RUN_ID_MATCH!=1 is blocked (fail-closed)."
    exit 1
  fi
  if [ -n "${UI_TRUTH_CLICK_INVENTORY_REPORT:-}" ]; then
    OPENVIBECODING_UI_TRUTH_GATE_STRICT="${OPENVIBECODING_CI_UI_TRUTH_GATE_STRICT:-1}" \
    OPENVIBECODING_UI_TRUTH_DISABLE_AUTO_LATEST="${OPENVIBECODING_CI_UI_TRUTH_DISABLE_AUTO_LATEST:-1}" \
    OPENVIBECODING_UI_TRUTH_REQUIRE_RUN_ID_MATCH="${OPENVIBECODING_CI_UI_TRUTH_REQUIRE_RUN_ID_MATCH:-1}" \
    OPENVIBECODING_UI_TRUTH_ENFORCE_FLAKE_POLICY="${OPENVIBECODING_CI_UI_TRUTH_ENFORCE_FLAKE_POLICY:-1}" \
    OPENVIBECODING_UI_TRUTH_P0_MAX_THRESHOLD_PERCENT="${OPENVIBECODING_CI_UI_TRUTH_P0_MAX_THRESHOLD_PERCENT:-0.5}" \
    OPENVIBECODING_UI_TRUTH_P1_MAX_THRESHOLD_PERCENT="${OPENVIBECODING_CI_UI_TRUTH_P1_MAX_THRESHOLD_PERCENT:-1.0}" \
    OPENVIBECODING_UI_TRUTH_P0_MIN_ITERATIONS="${OPENVIBECODING_CI_UI_TRUTH_P0_MIN_ITERATIONS:-8}" \
    OPENVIBECODING_UI_TRUTH_P1_MIN_ITERATIONS="${OPENVIBECODING_CI_UI_TRUTH_P1_MIN_ITERATIONS:-8}" \
    OPENVIBECODING_UI_P0_REPORT="${P0_REPORT_PATH}" \
    OPENVIBECODING_UI_P1_REPORT="${P1_REPORT_PATH}" \
    OPENVIBECODING_UI_CHAIN_REPORT="${OPENVIBECODING_CI_UI_CHAIN_REPORT:-}" \
    OPENVIBECODING_UI_TAURI_REPORT="${OPENVIBECODING_CI_UI_TAURI_REPORT:-}" \
    OPENVIBECODING_UI_CLICK_INVENTORY_REPORT="${UI_TRUTH_CLICK_INVENTORY_REPORT}" \
    OPENVIBECODING_UI_CLICK_INVENTORY_REQUIRED="${UI_TRUTH_CLICK_INVENTORY_REQUIRED}" \
    bash scripts/ui_e2e_truth_gate.sh
  else
    OPENVIBECODING_UI_TRUTH_GATE_STRICT="${OPENVIBECODING_CI_UI_TRUTH_GATE_STRICT:-1}" \
    OPENVIBECODING_UI_TRUTH_DISABLE_AUTO_LATEST="${OPENVIBECODING_CI_UI_TRUTH_DISABLE_AUTO_LATEST:-1}" \
    OPENVIBECODING_UI_TRUTH_REQUIRE_RUN_ID_MATCH="${OPENVIBECODING_CI_UI_TRUTH_REQUIRE_RUN_ID_MATCH:-1}" \
    OPENVIBECODING_UI_TRUTH_ENFORCE_FLAKE_POLICY="${OPENVIBECODING_CI_UI_TRUTH_ENFORCE_FLAKE_POLICY:-1}" \
    OPENVIBECODING_UI_TRUTH_P0_MAX_THRESHOLD_PERCENT="${OPENVIBECODING_CI_UI_TRUTH_P0_MAX_THRESHOLD_PERCENT:-0.5}" \
    OPENVIBECODING_UI_TRUTH_P1_MAX_THRESHOLD_PERCENT="${OPENVIBECODING_CI_UI_TRUTH_P1_MAX_THRESHOLD_PERCENT:-1.0}" \
    OPENVIBECODING_UI_TRUTH_P0_MIN_ITERATIONS="${OPENVIBECODING_CI_UI_TRUTH_P0_MIN_ITERATIONS:-8}" \
    OPENVIBECODING_UI_TRUTH_P1_MIN_ITERATIONS="${OPENVIBECODING_CI_UI_TRUTH_P1_MIN_ITERATIONS:-8}" \
    OPENVIBECODING_UI_P0_REPORT="${P0_REPORT_PATH}" \
    OPENVIBECODING_UI_P1_REPORT="${P1_REPORT_PATH}" \
    OPENVIBECODING_UI_CHAIN_REPORT="${OPENVIBECODING_CI_UI_CHAIN_REPORT:-}" \
    OPENVIBECODING_UI_TAURI_REPORT="${OPENVIBECODING_CI_UI_TAURI_REPORT:-}" \
    OPENVIBECODING_UI_CLICK_INVENTORY_REQUIRED="${UI_TRUTH_CLICK_INVENTORY_REQUIRED}" \
    bash scripts/ui_e2e_truth_gate.sh
  fi
  python3 scripts/ui_regression_trend_append.py \
    --profile "${UI_REGRESSION_PROFILE:-pr}" \
    --p0-report "${P0_REPORT_PATH}" \
    --p1-report "${P1_REPORT_PATH}" \
    --truth-report "${OPENVIBECODING_UI_TRUTH_GATE_REPORT:-.runtime-cache/test_output/ui_regression/ui_e2e_truth_gate.json}"
  echo "✅ [STEP 8.9/12] Completed"
}
